// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruryofzrqqwvshiminis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cnlvZnpycXF3dnNoaW1pbmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjQ5NjYsImV4cCI6MjA2MDMwMDk2Nn0.-XpciaEflx2Mb7HMJ5oThx-J5UbKnczX1ABgvYKhFIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);